config/routes.rb
GreaterThan::Application.routes.draw do
  devise_for :users, :controllers => { :registrations => "registrations" }

  root 'static_pages#home'

  resources :topics
  resources :conversations
  resources :replies

  get 'profile' => 'profiles#show'
end

app/models/conversation.rb
class Conversation < ActiveRecord::Base
  belongs_to :topic
  has_many :replies
end

app/models/profile.rb
class Profile < ActiveRecord::Base
  validates_presence_of :age, :location
  belongs_to :user
end

app/models/reply.rb
class Reply < ActiveRecord::Base
  belongs_to :conversation
end

app/models/topic.rb
class Topic < ActiveRecord::Base
  has_many :conversations
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_one :profile
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
  def new
    @topic_id = params[:topic_id]
  end

  def create
    @topic_id = params[:conversation][:topic_id]
    @topic = Topic.find(@topic_id)
    @conversation = @topic.conversations.create(conversation_params)
    redirect_to @topic
  end

  def show
    @conversation = Conversation.find(params[:id])
    @replies = @conversation.replies.order('created_at DESC')

  end

  private
    def conversation_params
      params.require(:conversation).permit(:title, :content)
    end

end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController

  def show
    @user = current_user
  end

end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController


  def create
    build_resource(sign_up_params)

    if resource.save
      yield resource if block_given?
      if resource.active_for_authentication?
        set_flash_message :notice, :signed_up if is_flashing_format?
        sign_up(resource_name, resource)
        respond_with resource, location: after_sign_up_path_for(resource)
      else
        set_flash_message :notice, :"signed_up_but_#{resource.inactive_message}" if is_flashing_format?
        expire_data_after_sign_in!
        respond_with resource, location: after_inactive_sign_up_path_for(resource)
      end
    else
      clean_up_passwords resource
      flash[:notice] = flash[:notice].to_a.concat resource.errors.full_messages
      redirect_to root_path(:failed => "y")
    end
  end


  protected

  def after_sign_up_path_for(resource)
    root_path
  end


  def after_inactive_sign_up_path_for(resource)
    root_path
  end

  private

  def sign_up_params
    params.require(resource_name).permit(:username, :email, :password, :first_name, :last_name)
  end
  def account_update_params
    params.require(:user).permit(:username, :email, :password, :first_name, :last_name)
  end
end

app/controllers/replies_controller.rb
class RepliesController < ApplicationController

  def new
    @conversation_id = params[:conversation_id]
  end

  def create
    @conversation_id = params[:reply][:conversation_id]
    @conversation = Conversation.find(@conversation_id)
    @reply = @conversation.replies.create(reply_params)
    redirect_to @conversation
  end

  private
    def reply_params
      params.require(:reply).permit(:content)
    end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    if user_signed_in?
      redirect_to topics_path
    end
  end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  def index
    @topics = Topic.all
  end

  def show
    @topic = Topic.find(params[:id])
    @conversations = @topic.conversations.order('created_at DESC')
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/conversations/new.html.haml
.container-fluid
  .row
    .col-md-4.col-md-offset-4
      %h1 Start a Conversation
      = form_for :conversation, url: conversations_path do |f|
        .form-group
          = f.text_field :title, placeholder: "Title", :class => "form-control"
        .form-group
          = f.text_area :content, placeholder: "Content", :class => "form-control"
        .form-group.text-center
          = f.hidden_field :topic_id, :value => @topic_id
          = f.submit 
        

app/views/conversations/show.html.haml
.container-fluid
  .row
    .col-md-1.col-md-offset-3
      .back-button.pull-right= link_to "<", @conversation.topic
    .col-md-4
      %table.table
        %thead
          %tr
            %th
              %span.h1= @conversation.title
              - if @conversation.content
                %span.h3= @conversation.content
        %tbody
          %tr
            %td= link_to "Add to conversation", new_reply_path(conversation_id: @conversation.id)
          - if @replies.any?
            - @replies.each do |reply|
              %tr
                %td
                  %span.h3= reply.content

app/views/layouts/_header.html.haml
%header
  %nav.navbar.navbar-default.navbar-fixed-top{role: "navigation"}
    .container-fluid
      .navbar-header
        %button.navbar-toggle{"data-target" => "#main-nav-collapse", "data-toggle" => "collapse", type: "button"}
          %span.sr-only Toggle navigation
          %span.icon-bar
          %span.icon-bar
          %span.icon-bar
        = link_to root_path, class: "navbar-brand" do
          %span I AM >
          %span.power-noun
      #main-nav-collapse.collapse.navbar-collapse
        %ul.nav.navbar-nav.navbar-right
          - if user_signed_in?
            %li= link_to "Profile", profile_path
            %li= link_to "Topics", topics_path
            %li= link_to "Logout", destroy_user_session_path, :method => :delete
          - else
            %li= link_to "Login", new_user_session_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title GreaterThan
    %link{href: "http://fonts.googleapis.com/css?family=Shadows+Into+Light", rel: "stylesheet", type: "text/css"}/
    = stylesheet_link_tag    "application", media: "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
    %meta{content: "width=device-width, initial-scale=1", name: "viewport"}
  %body{class: controller_name + "-" + controller.action_name}
    = render 'layouts/header'
    - flash.each do |name, msg|
      - if msg.class == Array
        - msg.each do |message|
          = content_tag :div, message, :id => "flash_#{name}", :class => "flash"
      - else
        #{content_tag :div, msg, :id => "flash_#{name}", :class => "flash"}
    = yield

app/views/profiles/show.html.haml
/%h1.text-center= "#{@user.first_name}'s Profile"
.container-fluid
  .row
    .col-sm-6.col-sm-offset-3.main-container
      .row.profile-top
        .profile-pic
          = image_tag("struggles.png", :class => "img-responsive profile-image img-circle")
        .name
          = @user.first_name
      .row
        .well
          %p Hey! I'm Joel. I'm 13 and I love movies, snowboarding, and pizza. Oh, and I've got a dog named Sushi. She's basically the devil (jkjk). Oh and I like to read. Books, you know, like Harry Potter and Lord of the Rings, etc. Peace!

      .row
        .well.interests
          \#snowboarding
          %br
          \#piano
          %br
          \#lordoftherings
          %br
          \#harrypotter
          %br
          \#switchfoot

app/views/replies/new.html.haml
.container-fluid
  .row
    .col-md-4.col-md-offset-4
      %h1.text-center Reply to Conversation
      = form_for :reply, url: replies_path do |f|
        .form-group
          = f.text_area :content, placeholder: "Content", :class => "form-control"
          = f.hidden_field :conversation_id, :value => @conversation_id
        .form-group.text-center
          = f.submit 
        

app/views/static_pages/home.html.haml
.container-fluid
  .row
    .col-md-4.col-md-offset-4
      - if user_signed_in?
      - else
        %h1.text-center.secondary Hello!
        = form_for(resource, :as => resource_name, :url => registration_path(resource_name)) do |f|
          = devise_error_messages!
          .form-group
            = f.text_field :first_name, :autofocus => true, placeholder: "First Name", :class => "form-control"
          .form-group
            = f.text_field :last_name, :autofocus => true, placeholder: "Last Name", :class => "form-control"
          .form-group
            = f.text_field :username, :autofocus => true, placeholder: "Username", :class => "form-control"
          .form-group
            = f.text_field :email, :autofocus => true, placeholder: "Email", :class => "form-control"
          .form-group
            = f.password_field :password, placeholder: "Password", :class => "form-control"
          .form-group.text-center
            = f.submit "Sign up", :class => "btn btn-lg btn-default"

app/views/topics/index-old.html.haml
.container-fluid
  .row
    .col-md-4.col-md-offset-4
      %h1.text-center Topics
      .row
        .col-sm-6
          .subject-box
            = image_tag("hobbies.png", :class => "img-responsive")
        .col-sm-6
          .subject-box
            = image_tag("stories.png", :class => "img-responsive")
      .row
        .col-sm-6.text-center
          %h2 Hobbies
        .col-sm-6.text-center
          %h2 Stories
      .row
        .col-sm-6
          .subject-box
            = image_tag("struggles.png", :class => "img-responsive")
        .col-sm-6
          .subject-box
            = image_tag("family.png", :class => "img-responsive")
      .row
        .col-sm-6.text-center
          %h2 Struggles
        .col-sm-6.text-center
          %h2 Family

app/views/topics/index.html.haml
.container-fluid
  .row
    .col-sm-6.col-sm-offset-3.main-container
      .row.profile-top
        .name
          Topics
      - @topics.each do |topic|
        .row
          .well.topic
            = link_to topic.title, topic

app/views/topics/show.html.haml
.container-fluid
  .row
    .col-sm-1.col-sm-offset-3.button-container
      %span.back-button.pull-right= link_to "<", topics_path
    .col-sm-4
      %table.table
        %thead
          %tr
            %th.h1= @topic.title
        %tbody
          %tr
            %td= link_to "Start new conversation", new_conversation_path(topic_id: @topic.id)
          - if @conversations.any?
            - @conversations.each do |convo|
              %tr
                %td
                  %span.conversation-item.h3= link_to convo.title, convo